### ISSUE TITLE
[BUG] - Failure to connect to introducer

### ISSUE THREAD

**Issue by nahvan** [Caldera-Network/caldera-blockchain#8] opened 2021-07-02 06:25 UTC
**Describe the bug**
Failure to connect to introducer 

**To Reproduce**
open gui or cli node, check logs

**Expected behavior**
sync up

**Desktop:**

- OS: Windows 10 Pro
- CPU: 5950x

2021-07-02T02:21:37.263 full_node deafwave.full_node.full_node: INFO     Received 1 peers from DNS seeder.
2021-07-02T02:21:45.305 full_node full_node_server        : INFO     Connected with introducer {'host': 'beta2_introducer.deafwave.net', 'port': 58620}
2021-07-02T02:21:45.501 full_node full_node_server        : INFO     Connection closed: beta2_introducer.deafwave.net, node id: 6bf7d6cf3a67f4017255cfa54bb607c3cddab7b59d5a57cffbf5e68a668ae72f
2021-07-02T02:21:45.503 full_node deafwave.full_node.full_node: INFO     peer disconnected {'host': '97.126.106.67', 'port': 58620}
2021-07-02T02:21:45.505 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '97.126.106.67', 'port': 58620}. Traceback (most recent call last):
  File "deafwave\server\server.py", line 579, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-07-02T02:21:58.362 full_node full_node_server        : INFO     Connected with introducer {'host': 'beta2_introducer.deafwave.net', 'port': 58620}
2021-07-02T02:21:58.561 full_node full_node_server        : INFO     Connection closed: beta2_introducer.deafwave.net, node id: 6bf7d6cf3a67f4017255cfa54bb607c3cddab7b59d5a57cffbf5e68a668ae72f
2021-07-02T02:21:58.563 full_node deafwave.full_node.full_node: INFO     peer disconnected None
2021-07-02T02:21:58.565 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "deafwave\server\server.py", line 579, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

![image](https://user-images.githubusercontent.com/82133693/124230395-f00d5d00-dadc-11eb-81a7-57193432b134.png)

**Comment by ChandlerFerry** [comment] 2021-07-02 19:35
I believe this is caused by two things.

1. No DNS Seeder at this time (WIP)
2. Too high difficulty for the current netspace

Testnet Two which just launched will validate 2, then I will continue working on 1.

**Comment by ChandlerFerry** [comment] 2021-07-22 00:57
Closing, has been resolved with DNS Seeder.

**Closed** 2021-07-22 00:57 UTC
Labels: bug
